name: uv
description: Install uv from our version
runs:
  using: composite
  steps:
    - name: Install Python for uv
      # This action reads the Python version from .python-version
      uses: actions/setup-python@v6
    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867
