#%%
from nuc_morph_analysis.analyses.mitotic_neighbors import example_dying_track_neighbors
from nuc_morph_analysis.analyses.mitotic_neighbors import example_mitotic_track_neighbors
from nuc_morph_analysis.analyses.mitotic_neighbors import example_timepoint_neighbors_of_dying
from nuc_morph_analysis.analyses.mitotic_neighbors import example_timepoint_of_neighbors_of_mitotic