name: PDM & Dependencies
description: Install PDM and dependencies
runs:
  using: composite
  steps:
    - uses: ./.github/actions/uv

    - name: Install dependencies
      shell: bash
      # --only-keep flag in case the environment is restored from a stale cache.
      run: uv sync
