name: Make requirements files

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - bioRxiv-v1
      - dev
    paths:
      - "uv.lock"

jobs:
  make-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/uv

      - name: Generate requirements.txt
        shell: bash
        run: uv export --format requirements.txt --no-hashes | grep -v '^ *#'> requirements.txt

      - name: Upload requirements files
        uses: actions/upload-artifact@v6
        with:
          name: requirements
          path: requirements.txt

  open-PR:
    needs: [make-requirements]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download requirements file
        uses: actions/download-artifact@v7
        with:
          name: requirements
          path: .

      - name: Clean-up CRLF
        shell: bash
        run: find requirements.txt -type f -exec sed -i 's/\r//g' {} \;

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          base: ${{ github.ref_name }}
          title: admin/requirements-update_${{ steps.timestamp.outputs.timestamp }}
          body: Updating requirements.txt.

            Due to some [challenges](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs),
            with getting this PR to trigger the tests, please manually close and re-open this PR.
          branch: admin/requirements-update_${{ steps.timestamp.outputs.timestamp }}
          commit-message: Updating requirements.txt after change to `uv.lock` was pushed to `${{ github.ref_name }}`
          delete-branch: true
