name: Do science

on:
  workflow_dispatch:

jobs:
  colony-area:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: ./.github/actions/dependencies

      - name: Run colony area workflow
        shell: bash
        run: pdm run python run_all_manuscript_workflows.py --only figure1_main_text

  error-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: ./.github/actions/dependencies
      - name: Run error workflow
        shell: bash
        run: pdm run python run_all_manuscript_workflows.py --only error
